FROM php:7.4.2-apache

RUN apt-get update && apt-get install -y libicu-dev && \
  docker-php-source extract && \
  docker-php-ext-install pdo_mysql && \
  docker-php-ext-configure intl && \
  docker-php-ext-install intl && \
  pecl install xdebug-2.9.2 && \
  docker-php-ext-enable xdebug && \
  docker-php-source delete && \
  a2enmod rewrite && \
  curl -sS https://getcomposer.org/installer | php && \
  mv composer.phar /usr/local/bin/composer